-- Oracle 19c+ Database Schema for Visitor Management System (VMS)

-- Sequence for VISITOR_ID
CREATE SEQUENCE visitor_seq START WITH 1 INCREMENT BY 1;

-- Creating the Visitors table
CREATE TABLE VISITORS (
    ID NUMBER PRIMARY KEY,
    
    -- Basic Information
    FULL_NAME VARCHAR2(100) NOT NULL,
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    PURPOSE_OF_VISIT VARCHAR2(100) NOT NULL,
    HOST_NAME VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2(255) NOT NULL,
    
    -- Nationality & Document Verification
    NATIONALITY VARCHAR2(20) NOT NULL, -- 'Indian' or 'Foreign Visitor'
    AADHAAR_NUMBER VARCHAR2(12),
    PAN_NUMBER VARCHAR2(10),
    PASSPORT_NUMBER VARCHAR2(20),
    VISA_NUMBER VARCHAR2(20),
    COUNTRY VARCHAR2(50),
    DOC_VERIFIED CHAR(1) DEFAULT 'N' CHECK (DOC_VERIFIED IN ('Y', 'N')), -- 'Y' if manually verified
    
    -- Photo Capture
    PHOTO_PATH VARCHAR2(255), -- Local path to offline storage, nullable initially
    
    -- Block Access Selection
    ALLOWED_BLOCKS VARCHAR2(500) NOT NULL, -- Comma-separated blocks or JSON
    
    -- Locker & Phone Deposit
    PHONE_DEPOSITED CHAR(1) DEFAULT 'N' CHECK (PHONE_DEPOSITED IN ('Y', 'N')),
    LOCKER_NUMBER VARCHAR2(20),
    
    -- Visit Validity
    PASS_VALID_FROM VARCHAR2(50) NOT NULL, -- e.g. '2026-03-07 10:00'
    PASS_VALID_UNTIL VARCHAR2(50) NOT NULL,
    MULTI_ENTRY_ALLOWED CHAR(1) DEFAULT 'N' CHECK (MULTI_ENTRY_ALLOWED IN ('Y', 'N')),
    
    -- Metadata
    STATUS VARCHAR2(30) DEFAULT 'WAITING_FOR_PHOTO' CHECK (STATUS IN ('WAITING_FOR_PHOTO', 'PASS_READY', 'VISITOR_INSIDE', 'VISITOR_EXITED')),
    CREATED_BY_OFFICER VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Index to optimize querying today's visitors for duplicates
CREATE INDEX idx_visitors_valid_from ON VISITORS (PASS_VALID_FROM);
CREATE INDEX idx_visitors_phone ON VISITORS (PHONE_NUMBER);

-- Commit
COMMIT;

-- User Master for RBAC
CREATE TABLE USER_MASTER (
    EMPID VARCHAR2(11) PRIMARY KEY,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1,
    DEFAULT_ROLE VARCHAR2(20),
    ROLE VARCHAR2(20)
);

-- Access Authorization Table
CREATE TABLE AUTHORIZATION (
    ID NUMBER PRIMARY KEY,
    EMPID VARCHAR2(11),
    SCREEN_ID VARCHAR2(50),
    ROLE_ID NUMBER,
    CONSTRAINT FK_AUTH_EMP FOREIGN KEY (EMPID) REFERENCES USER_MASTER(EMPID)
);
CREATE SEQUENCE auth_seq START WITH 1 INCREMENT BY 1;

-- Seed Data (Password hashes are for 'GTRE123')
INSERT INTO USER_MASTER (EMPID, PASSWORD_HASH, FULL_NAME, ENABLED, ROLE) VALUES ('EMP01', '$2b$12$Z0Kj/yJ.kGkZ0C.K6v6.o.E.K5mQyYV.zT12J.jU2.hFv2y2b6z8u', 'System Administrator', 1, 'admin');
INSERT INTO USER_MASTER (EMPID, PASSWORD_HASH, FULL_NAME, ENABLED, ROLE) VALUES ('EMP02', '$2b$12$Z0Kj/yJ.kGkZ0C.K6v6.o.E.K5mQyYV.zT12J.jU2.hFv2y2b6z8u', 'Security Officer', 1, 'officer');
INSERT INTO USER_MASTER (EMPID, PASSWORD_HASH, FULL_NAME, ENABLED, ROLE) VALUES ('EMP03', '$2b$12$Z0Kj/yJ.kGkZ0C.K6v6.o.E.K5mQyYV.zT12J.jU2.hFv2y2b6z8u', 'Front Desk Reception', 1, 'reception');

INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'dashboard.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'visitor_request.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'officer_visitors.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'reception_dashboard.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'todays_visitors.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'attendance.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'gate_scanners.html', 1);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP01', 'admin_login.html', 1);

INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP02', 'dashboard.html', 2);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP02', 'visitor_request.html', 2);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP02', 'officer_visitors.html', 2);

INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP03', 'dashboard.html', 3);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP03', 'reception_dashboard.html', 3);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP03', 'todays_visitors.html', 3);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP03', 'attendance.html', 3);
INSERT INTO AUTHORIZATION (ID, EMPID, SCREEN_ID, ROLE_ID) VALUES (auth_seq.NEXTVAL, 'EMP03', 'gate_scanners.html', 3);

COMMIT;
