-- Oracle 19c+ Database Schema for Visitor Request Module

-- Sequence for Requisition Number auto-increment part
CREATE SEQUENCE requisition_num_seq START WITH 1 INCREMENT BY 1;

-- Creating the visitor_requests table
CREATE TABLE VISITOR_REQUESTS (
    REQUISITION_ID NUMBER PRIMARY KEY,
    REQUISITION_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    REQUESTED_BY VARCHAR2(100) NOT NULL,
    REQUEST_DATE VARCHAR2(30) NOT NULL, -- DD-MMM-YYYY
    OFFICER_TO_MEET VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100) NOT NULL,
    PURPOSE VARCHAR2(50) NOT NULL,
    VALID_FROM VARCHAR2(50) NOT NULL,
    VALID_UPTO VARCHAR2(50) NOT NULL,
    VISITOR_CATEGORY VARCHAR2(50) NOT NULL,
    VISITOR_NAME VARCHAR2(100) NOT NULL,
    ORGANISATION VARCHAR2(100) NOT NULL,
    COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    MOBILE VARCHAR2(20) NOT NULL,
    REMARKS VARCHAR2(500),
    
    -- Metadata
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Index for requisition number
CREATE INDEX idx_req_num ON VISITOR_REQUESTS (REQUISITION_NUMBER);

-- Initial Officers Database for dropdown and auto-fill location
CREATE TABLE OFFICERS (
    OFFICER_ID NUMBER PRIMARY KEY,
    OFFICER_NAME VARCHAR2(100) NOT NULL,
    OFFICER_CORP_NAME VARCHAR2(100),
    LOCATION VARCHAR2(100) NOT NULL
);

INSERT INTO OFFICERS (OFFICER_ID, OFFICER_NAME, OFFICER_CORP_NAME, LOCATION) VALUES (1, 'BIJEESH K', 'SC C', 'Block A, 2nd Floor');
INSERT INTO OFFICERS (OFFICER_ID, OFFICER_NAME, OFFICER_CORP_NAME, LOCATION) VALUES (2, 'DR. A. SHARMA', 'DIRECTOR', 'Main Building, Ground Floor');
INSERT INTO OFFICERS (OFFICER_ID, OFFICER_NAME, OFFICER_CORP_NAME, LOCATION) VALUES (3, 'M. SINGH', 'HR HEAD', 'Admin Block, 1st Floor');

-- Commit
COMMIT;
